#!/bin/bash

xdg_config_home="$HOME/.config"

mkdir -p "$xdg_config_home"

# link everything to $XDG_CONFIG_HOME
test -L "$xdg_config_home/aerospace" || ln -sfn "$PWD/aerospace" $_
test -L "$xdg_config_home/bash" || ln -sfn "$PWD/bash" $_
test -L "$xdg_config_home/bin" || ln -sfn "$PWD/bin" $_
test -L "$xdg_config_home/git" || ln -sfn "$PWD/git" $_
test -L "$xdg_config_home/kitty" || ln -sfn "$PWD/kitty" $_
test -L "$xdg_config_home/nvim" || ln -sfn "$PWD/nvim" $_
test -L "$xdg_config_home/tmux" || ln -sfn "$PWD/tmux" $_

# link bash profile and bash rc explicitly
test -L "$HOME/.bashrc" || ln -sfn "$xdg_config_home/bash/bashrc" $_
test -L "$HOME/.bash_profile" || ln -sfn "$xdg_config_home/bash/bash_profile" $_

# make all custom binaries executable
for d in $(find "bin" -type f); do chmod +x $d; done

# assert local bin is in path , which is not necessarily be true on all systems?
if [[ $PATH != *":$bin"* ]]; then
  echo "export PATH=\$PATH:$bin" >> ~/.bashrc
fi

