#!/bin/bash

xdg_config_home="$HOME/.config"
bin="$xdg_config_home/bin"

mkdir -p "$xdg_config_home"

# link everything to $XDG_CONFIG_HOME
test -L "$xdg_config_home/aerospace" || ln -sfn "$PWD/aerospace" $_
test -L "$xdg_config_home/bash" || ln -sfn "$PWD/bash" $_
test -L "$xdg_config_home/bin" || ln -sfn "$PWD/bin" $_
test -L "$xdg_config_home/git" || ln -sfn "$PWD/git" $_
test -L "$xdg_config_home/kitty" || ln -sfn "$PWD/kitty" $_
test -L "$xdg_config_home/nvim" || ln -sfn "$PWD/nvim" $_
test -L "$xdg_config_home/tmux" || ln -sfn "$PWD/tmux" $_
test -L "$xdg_config_home/zsh" || ln -sfn "$PWD/zsh" $_

# link bash profile and bash rc explicitly
test -L "$HOME/.bashrc" || ln -sfn "$xdg_config_home/bash/bashrc" $_
test -L "$HOME/.bash_profile" || ln -sfn "$xdg_config_home/bash/bash_profile" $_
test -L "$HOME/.zshenv" || ln -sfn "$xdg_config_home/zsh/.zshenv" $_

# symlink vim/ to ~/.vim
test -L "$HOME/.vim" || ln -sfn "$PWD/vim" $_

# vim plugins
if [[ ! -f "$HOME/.vim/autoload/plug.vim" ]]; then
	curl -fLo "$HOME/.vim/autoload/plug.vim" --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  vim +'PlugInstall --sync' +qa
fi
vim -es +'silent! PlugInstall --sync' +qa

# make all custom binaries executable
find "bin" -type f | xargs chmod +x

# install all dependencies via homebrew
brew bundle

# git submodule
git submodule update --init --recursive

# init undodir
mkdir -p $HOME/.vim/undodir

if [[ -f "$PWD/macos/defaults" ]]; then
    bash $_
else
    echo "error: unable to find macos defaults"
fi
