eval $(/opt/homebrew/bin/brew shellenv)

export PATH="$PATH:$(go env GOPATH)/bin"
export PATH="$PATH:$HOME/local/bin"

export BASH_SILENCE_DEPRECATION_WARNING=1
export PYENV_ROOT=/opt/homebrew/bin

# we really should not do this, but whatever
export TERM=xterm-256color

source ~/.config/bash/aliases

test -f ~/.git-completion.bash && . $_ 2> /dev/null

if which fzf 2> /dev/null; then
	eval "$(fzf --bash)"
fi

if which pyenv 2> /dev/null; then
	eval "$(pyenv init -)"
	pyenv global 3.11.9
fi

if which direnv 2> /dev/null; then
	eval "$(direnv hook bash)"
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH="/opt/homebrew/opt/node@20/bin:$PATH"
export PATH="$PATH:/Users/anshul.kamath/.config/bin"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
